# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ktheory-vlad}
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Davis", "Eric Hodel", "Wilson Bilkovich", "Aaron Suggs"]
  s.date = %q{2009-12-05}
  s.description = %q{
Vlad the Deployer is pragmatic application deployment automation,
without mercy. Much like Capistrano, but with 1/10th the
complexity. Vlad integrates seamlessly with Rake, and uses familiar
and standard tools like ssh and rsync. This is a fork of vlad maintained by
Aaron Suggs. See PATCHES.txt for more info""
}
  s.email = ["ryand-ruby@zenspider.com", "drbrain@segment7.net", "wilson@supremetyrant.com", "aaron@ktheory.com"]
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    ".autotest",
     "History.txt",
     "Manifest.txt",
     "PATCHES.txt",
     "README.txt",
     "Rakefile",
     "VERSION",
     "considerations.txt",
     "doco/deploying-merb-with-vlad.txt",
     "doco/deploying-sinatra-with-vlad.txt",
     "doco/faq.txt",
     "doco/getting_started.txt",
     "doco/migration.txt",
     "doco/perforce.txt",
     "doco/variables.txt",
     "ktheory-vlad.gemspec",
     "lib/rake_remote_task.rb",
     "lib/vlad.rb",
     "lib/vlad/apache.rb",
     "lib/vlad/core.rb",
     "lib/vlad/darcs.rb",
     "lib/vlad/git.rb",
     "lib/vlad/god.rb",
     "lib/vlad/lighttpd.rb",
     "lib/vlad/maintenance.rb",
     "lib/vlad/merb.rb",
     "lib/vlad/mercurial.rb",
     "lib/vlad/mongrel.rb",
     "lib/vlad/nginx.rb",
     "lib/vlad/passenger.rb",
     "lib/vlad/perforce.rb",
     "lib/vlad/subversion.rb",
     "lib/vlad/thin.rb",
     "lib/vlad_test_case.rb",
     "test/test_rake_remote_task.rb",
     "test/test_vlad.rb",
     "test/test_vlad_git.rb",
     "test/test_vlad_mercurial.rb",
     "test/test_vlad_perforce.rb",
     "test/test_vlad_subversion.rb",
     "vladdemo.sh"
  ]
  s.homepage = %q{http://github.com/ktheory/vlad}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Vlad the Deployer is pragmatic application deployment automation, without mercy [ktheory's fork]}
  s.test_files = [
    "test/test_rake_remote_task.rb",
     "test/test_vlad.rb",
     "test/test_vlad_git.rb",
     "test/test_vlad_mercurial.rb",
     "test/test_vlad_perforce.rb",
     "test/test_vlad_subversion.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, ["~> 0.8.0"])
      s.add_runtime_dependency(%q<open4>, ["~> 0.9.0"])
    else
      s.add_dependency(%q<rake>, ["~> 0.8.0"])
      s.add_dependency(%q<open4>, ["~> 0.9.0"])
    end
  else
    s.add_dependency(%q<rake>, ["~> 0.8.0"])
    s.add_dependency(%q<open4>, ["~> 0.9.0"])
  end
end

